import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  FileText,
  Clock,
  Rocket,
  ShieldCheck,
  CheckCircle,
  AlertCircle,
  MoreVertical,
  ChevronLeft,
  ChevronRight,
  Search,
  Download,
  Plus,
  Lock,
  Users,
  DollarSign,
  BarChart3,
  Settings,
  FileSignature,
} from 'lucide-react';
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
} from 'recharts';
import Sidebar from '@/components/admin/Sidebar';
import TopBar from '@/components/admin/TopBar';
import type { AdminView } from '@/components/admin/Sidebar';

const ease = [0.16, 1, 0.3, 1] as [number, number, number, number];

/* ─── Activity chart data ─── */
const activityData = [
  { day: 'Jun 1', docs: 3 }, { day: 'Jun 2', docs: 5 }, { day: 'Jun 3', docs: 2 },
  { day: 'Jun 4', docs: 8 }, { day: 'Jun 5', docs: 6 }, { day: 'Jun 6', docs: 4 },
  { day: 'Jun 7', docs: 7 }, { day: 'Jun 8', docs: 9 }, { day: 'Jun 9', docs: 5 },
  { day: 'Jun 10', docs: 11 }, { day: 'Jun 11', docs: 8 }, { day: 'Jun 12', docs: 6 },
  { day: 'Jun 13', docs: 10 }, { day: 'Jun 14', docs: 7 }, { day: 'Jun 15', docs: 12 },
  { day: 'Jun 16', docs: 9 }, { day: 'Jun 17', docs: 5 }, { day: 'Jun 18', docs: 8 },
  { day: 'Jun 19', docs: 6 }, { day: 'Jun 20', docs: 10 }, { day: 'Jun 21', docs: 7 },
  { day: 'Jun 22', docs: 4 }, { day: 'Jun 23', docs: 9 }, { day: 'Jun 24', docs: 11 },
  { day: 'Jun 25', docs: 6 }, { day: 'Jun 26', docs: 8 }, { day: 'Jun 27', docs: 5 },
  { day: 'Jun 28', docs: 7 }, { day: 'Jun 29', docs: 10 }, { day: 'Jun 30', docs: 8 },
];

/* ─── Donut chart data ─── */
const statusData = [
  { name: 'Approved', value: 89, color: '#FFFFFF' },
  { name: 'Pending', value: 24, color: '#FFFFFF' },
  { name: 'Draft', value: 18, color: '#333333' },
];

/* ─── Activity feed data ─── */
const activityFeed = [
  { id: 1, action: "Document '4.2 Risk Assessment' approved by Risk Committee", time: '2 hours ago', type: 'approved' },
  { id: 2, action: "Phase Gate 2 milestone 'Custodial Framework' completed", time: '3 hours ago', type: 'complete' },
  { id: 3, action: "New exhibit 'Tokenomics Diagram v3' uploaded to Binder 7", time: '5 hours ago', type: 'upload' },
  { id: 4, action: "Compliance review pending for Document 6.1", time: '6 hours ago', type: 'pending' },
  { id: 5, action: "SubDAO structure updated by Admin User", time: '8 hours ago', type: 'approved' },
  { id: 6, action: "Launch Gate 1 checklist submitted for review", time: '10 hours ago', type: 'pending' },
  { id: 7, action: "Security audit report generated by System", time: '12 hours ago', type: 'upload' },
  { id: 8, action: "Document '3.1 Regulatory Classification' approved", time: '1 day ago', type: 'approved' },
];

/* ─── Phase gate data ─── */
const phases = [
  { name: 'Phase 0: Internal Sandbox', progress: 100, color: '#FFFFFF' },
  { name: 'Phase 1: Crypto Non-Custodial', progress: 85, color: '#FFFFFF' },
  { name: 'Phase 2: Custodial Hybrid', progress: 60, color: '#FFFFFF' },
  { name: 'Phase 3: US Approved State', progress: 30, color: '#FFFFFF' },
  { name: 'Phase 4: National Rollout', progress: 0, color: '#333333' },
  { name: 'Phase 5: Global Expansion', progress: 0, color: '#333333' },
  { name: 'Phase 6: Full Autonomy', progress: 0, color: '#333333' },
  { name: 'Phase 7: DAO Handover', progress: 0, color: '#333333' },
];

/* ─── Document table mock data ─── */
interface DocumentRow {
  id: number;
  ref: string;
  title: string;
  binder: string;
  binderNum: number;
  status: 'Approved' | 'Pending' | 'Draft';
  owner: string;
  updated: string;
}

const documentsData: DocumentRow[] = [
  { id: 1, ref: '1.1', title: 'Corporate Structure Memo', binder: 'Treasury', binderNum: 1, status: 'Approved', owner: 'Admin', updated: 'Jun 15, 2025' },
  { id: 2, ref: '2.1', title: 'Regulatory Classification', binder: 'Governance', binderNum: 2, status: 'Approved', owner: 'Admin', updated: 'Jun 14, 2025' },
  { id: 3, ref: '3.1', title: 'SORME Engine Specification', binder: 'Technical', binderNum: 3, status: 'Approved', owner: 'System', updated: 'Jun 13, 2025' },
  { id: 4, ref: '4.1', title: 'SubDAO Organization Chart', binder: 'Org Chart', binderNum: 4, status: 'Approved', owner: 'Admin', updated: 'Jun 12, 2025' },
  { id: 5, ref: '5.1', title: 'Legal Agreement v2.4', binder: 'Legal', binderNum: 5, status: 'Pending', owner: 'Admin', updated: 'Jun 11, 2025' },
  { id: 6, ref: '6.1', title: 'Compliance Checklist Q2', binder: 'Compliance', binderNum: 6, status: 'Draft', owner: 'System', updated: 'Jun 10, 2025' },
  { id: 7, ref: '7.1', title: 'Launch Gate 3 Checklist', binder: 'Operations', binderNum: 7, status: 'Pending', owner: 'User', updated: 'Jun 9, 2025' },
  { id: 8, ref: '8.1', title: 'Security Audit Report', binder: 'Security', binderNum: 8, status: 'Approved', owner: 'System', updated: 'Jun 8, 2025' },
  { id: 9, ref: '9.1', title: 'Masterclass EP1 Recording', binder: 'Education', binderNum: 9, status: 'Approved', owner: 'User', updated: 'Jun 7, 2025' },
  { id: 10, ref: '10.1', title: 'Revenue Share Overview', binder: 'Finance', binderNum: 10, status: 'Approved', owner: 'Admin', updated: 'Jun 6, 2025' },
];

/* ─── Stat cards ─── */
function StatsCards() {
  const stats = [
    { icon: FileText, iconBg: 'rgba(0,53,148,0.15)', value: '131', label: 'Total Documents', trend: '+12 from last week' },
    { icon: Clock, iconBg: 'rgba(245,158,11,0.15)', value: '24', label: 'Pending Approvals', trend: '5 urgent' },
    { icon: Rocket, iconBg: 'rgba(16,185,129,0.15)', value: '3 of 8', label: 'Active Phases', trend: 'Phase 2 in progress' },
    { icon: ShieldCheck, iconBg: 'rgba(0,53,148,0.15)', value: '94%', label: 'Compliance Score', trend: '+2% this month' },
  ];

  return (
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 p-6">
      {stats.map((s, i) => {
        const Icon = s.icon;
        return (
          <motion.div
            key={s.label}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3, delay: i * 0.05, ease }}
            className="bg-usa-elevated border border-usa-border rounded-xl p-5 hover:-translate-y-0.5 transition-transform"
          >
            <div className="w-10 h-10 rounded-[10px] flex items-center justify-center" style={{ backgroundColor: s.iconBg }}>
              <Icon size={20} className="text-usa-blue" strokeWidth={1.5} />
            </div>
            <p className="text-[28px] font-bold text-white mt-3 leading-none">{s.value}</p>
            <p className="text-xs text-usa-silver mt-1">{s.label}</p>
            <p className="text-[11px] text-usa-muted mt-1">{s.trend}</p>
          </motion.div>
        );
      })}
    </div>
  );
}

/* ─── Charts section ─── */
function ChartsSection() {
  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 px-6">
      {/* Line chart */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.4, delay: 0.2, ease }}
        className="lg:col-span-2 bg-usa-elevated border border-usa-border rounded-xl p-5"
      >
        <h3 className="text-sm font-semibold text-white">30-Day Activity</h3>
        <div className="mt-4" style={{ height: 200 }}>
          <ResponsiveContainer width="100%" height="100%">
            <LineChart data={activityData}>
              <CartesianGrid strokeDasharray="3 3" stroke="#333333" />
              <XAxis dataKey="day" tick={{ fill: '#888888', fontSize: 10 }} stroke="#333333" interval={4} />
              <YAxis tick={{ fill: '#888888', fontSize: 10 }} stroke="#333333" />
              <Tooltip
                contentStyle={{ backgroundColor: '#1a1a1a', border: '1px solid #333333', borderRadius: '6px', fontSize: '12px' }}
                itemStyle={{ color: '#FFFFFF' }}
                labelStyle={{ color: '#B0B7BC' }}
              />
              <Line
                type="monotone"
                dataKey="docs"
                stroke="#FFFFFF"
                strokeWidth={2}
                dot={{ fill: '#FFFFFF', r: 3 }}
                activeDot={{ r: 5, fill: '#FFFFFF' }}
              />
            </LineChart>
          </ResponsiveContainer>
        </div>
      </motion.div>

      {/* Donut chart */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.4, delay: 0.3, ease }}
        className="bg-usa-elevated border border-usa-border rounded-xl p-5"
      >
        <h3 className="text-sm font-semibold text-white">Document Status</h3>
        <div className="mt-4 flex flex-col items-center" style={{ height: 160 }}>
          <ResponsiveContainer width="100%" height="100%">
            <PieChart>
              <Pie
                data={statusData}
                cx="50%"
                cy="50%"
                innerRadius={45}
                outerRadius={65}
                paddingAngle={3}
                dataKey="value"
                stroke="none"
              >
                {statusData.map((entry, index) => (
                  <Cell key={`cell-${index}`} fill={entry.color} />
                ))}
              </Pie>
              <Tooltip
                contentStyle={{ backgroundColor: '#1a1a1a', border: '1px solid #333333', borderRadius: '6px', fontSize: '12px' }}
                itemStyle={{ color: '#FFFFFF' }}
              />
            </PieChart>
          </ResponsiveContainer>
        </div>
        <div className="flex items-center justify-center gap-4 mt-2">
          {statusData.map((s) => (
            <div key={s.name} className="flex items-center gap-1.5">
              <span className="w-2 h-2 rounded-full" style={{ backgroundColor: s.color }} />
              <span className="text-[11px] text-usa-silver">{s.name}</span>
            </div>
          ))}
        </div>
      </motion.div>
    </div>
  );
}

/* ─── Recent activity ─── */
function RecentActivity() {
  const getIcon = (type: string) => {
    switch (type) {
      case 'approved': return <CheckCircle size={16} className="text-[#FFFFFF]" />;
      case 'pending': return <AlertCircle size={16} className="text-[#FFFFFF]" />;
      case 'upload': return <FileText size={16} className="text-usa-blue" />;
      case 'complete': return <CheckCircle size={16} className="text-[#FFFFFF]" />;
      default: return <FileText size={16} className="text-usa-silver" />;
    }
  };

  const getDotColor = (type: string) => {
    switch (type) {
      case 'approved': case 'complete': return 'bg-[#FFFFFF]';
      case 'pending': return 'bg-[#FFFFFF]';
      case 'upload': return 'bg-usa-blue';
      default: return 'bg-usa-muted';
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.3, delay: 0.4, ease }}
      className="mx-6 mt-4 mb-4 bg-usa-elevated border border-usa-border rounded-xl p-5"
    >
      <h3 className="text-xs font-semibold text-usa-silver tracking-[0.12em] uppercase mb-3">Recent Activity</h3>
      <div className="divide-y divide-usa-border/50">
        {activityFeed.map((item) => (
          <div key={item.id} className="flex items-center gap-3 py-3">
            <div className={`w-9 h-9 rounded-full flex items-center justify-center flex-shrink-0 ${getDotColor(item.type)} bg-opacity-10`}>
              {getIcon(item.type)}
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-[13px] text-white truncate">{item.action}</p>
              <p className="text-[11px] text-usa-muted">{item.time}</p>
            </div>
          </div>
        ))}
      </div>
    </motion.div>
  );
}

/* ─── Phase gate progress ─── */
function PhaseGateProgress() {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.3, delay: 0.5, ease }}
      className="mx-6 mb-6 bg-usa-elevated border border-usa-border rounded-xl p-5"
    >
      <h3 className="text-xs font-semibold text-usa-silver tracking-[0.12em] uppercase mb-4">Phase Gates</h3>
      <div className="space-y-4">
        {phases.map((phase) => (
          <div key={phase.name}>
            <div className="flex items-center justify-between mb-1.5">
              <span className="text-[13px] text-white font-medium">{phase.name}</span>
              <span className="text-xs text-usa-silver">{phase.progress}%</span>
            </div>
            <div className="h-2 bg-usa-border rounded-full overflow-hidden">
              <motion.div
                initial={{ width: 0 }}
                animate={{ width: `${phase.progress}%` }}
                transition={{ duration: 0.8, ease }}
                className="h-full rounded-full"
                style={{ backgroundColor: phase.color }}
              />
            </div>
          </div>
        ))}
      </div>
    </motion.div>
  );
}

/* ─── Dashboard view ─── */
function DashboardView() {
  return (
    <div>
      <div className="px-6 pt-6">
        <h2 className="text-2xl font-bold text-white">Dashboard</h2>
        <p className="text-sm text-usa-silver mt-1">Overview of platform documents, compliance, and activity</p>
      </div>
      <StatsCards />
      <ChartsSection />
      <RecentActivity />
      <PhaseGateProgress />
    </div>
  );
}

/* ─── Documents view ─── */
function DocumentsView() {
  const [searchTerm, setSearchTerm] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 10;

  const filtered = documentsData.filter((d) =>
    d.title.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const statusBadge = (status: string) => {
    switch (status) {
      case 'Approved':
        return 'bg-[rgba(16,185,129,0.15)] text-[#FFFFFF]';
      case 'Pending':
        return 'bg-[rgba(245,158,11,0.15)] text-[#FFFFFF]';
      case 'Draft':
        return 'bg-[rgba(107,114,128,0.15)] text-usa-muted';
      default:
        return 'bg-usa-elevated text-usa-silver';
    }
  };

  return (
    <div className="p-6">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <h2 className="text-2xl font-bold text-white">Documents</h2>
          <span className="text-xs bg-usa-blue text-white px-2.5 py-0.5 rounded-full">131</span>
        </div>
        <button className="h-9 bg-usa-blue text-white text-sm font-semibold px-4 rounded-lg flex items-center gap-2 hover:brightness-110 transition-all">
          <Plus size={16} strokeWidth={2} />
          Add Document
        </button>
      </div>

      {/* Filter bar */}
      <div className="flex flex-wrap items-center gap-3 mb-4">
        <div className="flex items-center gap-2 flex-1 min-w-[200px] bg-usa-elevated border border-usa-border rounded-lg px-3 h-9">
          <Search size={16} className="text-usa-muted" />
          <input
            type="text"
            placeholder="Search documents..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="bg-transparent text-white text-sm flex-1 outline-none placeholder:text-usa-muted"
          />
        </div>
        <select className="h-9 bg-usa-elevated border border-usa-border rounded-lg px-3 text-white text-[13px] outline-none">
          <option>All Binders</option>
          {Array.from({ length: 10 }, (_, i) => (
            <option key={i}>Binder {i + 1}</option>
          ))}
        </select>
        <select className="h-9 bg-usa-elevated border border-usa-border rounded-lg px-3 text-white text-[13px] outline-none">
          <option>All Status</option>
          <option>Approved</option>
          <option>Pending</option>
          <option>Draft</option>
        </select>
        <button className="h-9 border border-usa-border text-usa-silver text-sm px-3 rounded-lg hover:border-usa-blue transition-colors flex items-center gap-2">
          <Download size={14} />
          Export
        </button>
      </div>

      {/* Table */}
      <div className="bg-usa-elevated border border-usa-border rounded-xl overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr className="bg-usa-card border-b border-usa-border">
                <th className="text-left text-xs font-semibold text-usa-silver tracking-[0.05em] uppercase px-4 py-3 w-10">
                  <input type="checkbox" className="rounded" />
                </th>
                <th className="text-left text-xs font-semibold text-usa-silver tracking-[0.05em] uppercase px-4 py-3">Document</th>
                <th className="text-left text-xs font-semibold text-usa-silver tracking-[0.05em] uppercase px-4 py-3">Binder</th>
                <th className="text-left text-xs font-semibold text-usa-silver tracking-[0.05em] uppercase px-4 py-3">Status</th>
                <th className="text-left text-xs font-semibold text-usa-silver tracking-[0.05em] uppercase px-4 py-3">Owner</th>
                <th className="text-left text-xs font-semibold text-usa-silver tracking-[0.05em] uppercase px-4 py-3">Last Updated</th>
                <th className="text-left text-xs font-semibold text-usa-silver tracking-[0.05em] uppercase px-4 py-3 w-16"></th>
              </tr>
            </thead>
            <tbody className="divide-y divide-usa-border/50">
              {filtered.map((doc, i) => (
                <motion.tr
                  key={doc.id}
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ delay: i * 0.02 }}
                  className="hover:bg-usa-card/50 transition-colors group"
                >
                  <td className="px-4 py-3">
                    <input type="checkbox" className="rounded" />
                  </td>
                  <td className="px-4 py-3">
                    <div>
                      <p className="text-[13px] text-white font-medium">{doc.title}</p>
                      <span className="inline-block mt-1 text-[10px] bg-usa-blue text-white px-1.5 py-0.5 rounded">{doc.ref}</span>
                    </div>
                  </td>
                  <td className="px-4 py-3">
                    <span className="text-[13px] text-usa-silver">Binder {doc.binderNum}</span>
                  </td>
                  <td className="px-4 py-3">
                    <span className={`inline-flex items-center text-[11px] font-semibold px-2 py-0.5 rounded-full ${statusBadge(doc.status)}`}>
                      {doc.status}
                    </span>
                  </td>
                  <td className="px-4 py-3">
                    <span className="text-[13px] text-usa-silver">{doc.owner}</span>
                  </td>
                  <td className="px-4 py-3">
                    <span className="text-xs text-usa-muted">{doc.updated}</span>
                  </td>
                  <td className="px-4 py-3">
                    <button className="w-8 h-8 flex items-center justify-center rounded-lg hover:bg-usa-elevated transition-colors opacity-0 group-hover:opacity-100">
                      <MoreVertical size={16} className="text-usa-silver" />
                    </button>
                  </td>
                </motion.tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Pagination */}
      <div className="flex items-center justify-between mt-4 px-1">
        <span className="text-xs text-usa-muted">Showing 1-{Math.min(itemsPerPage, filtered.length)} of 131 documents</span>
        <div className="flex items-center gap-2">
          <button className="w-9 h-9 bg-usa-elevated border border-usa-border rounded-md flex items-center justify-center text-white hover:bg-usa-card transition-colors">
            <ChevronLeft size={16} />
          </button>
          {[1, 2, 3, 4, 5].map((p) => (
            <button
              key={p}
              onClick={() => setCurrentPage(p)}
              className={`w-9 h-9 rounded-md flex items-center justify-center text-sm font-medium transition-colors ${
                currentPage === p ? 'bg-usa-blue text-white' : 'bg-usa-elevated border border-usa-border text-white hover:bg-usa-card'
              }`}
            >
              {p}
            </button>
          ))}
          <button className="w-9 h-9 bg-usa-elevated border border-usa-border rounded-md flex items-center justify-center text-white hover:bg-usa-card transition-colors">
            <ChevronRight size={16} />
          </button>
        </div>
      </div>
    </div>
  );
}

/* ─── Placeholder view ─── */
function PlaceholderView({ title, subtitle, icon: Icon }: { title: string; subtitle: string; icon: React.ElementType }) {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.3, ease }}
      className="flex flex-col items-center justify-center py-24 px-6"
    >
      <div className="w-16 h-16 rounded-2xl bg-usa-elevated border border-usa-border flex items-center justify-center mb-4">
        <Icon size={32} className="text-usa-blue" strokeWidth={1.5} />
      </div>
      <h2 className="text-2xl font-bold text-white mb-2">{title}</h2>
      <p className="text-sm text-usa-silver mb-6 text-center max-w-md">{subtitle}</p>
      <div className="inline-flex items-center gap-2 px-4 py-2 bg-usa-elevated border border-usa-border rounded-lg">
        <span className="text-xs text-usa-muted">Coming Soon</span>
      </div>
    </motion.div>
  );
}

/* ─── Compliance view ─── */
function ComplianceView() {
  const scores = [
    { label: 'Overall Score', value: '94%', sub: 'Target: 95%' },
    { label: 'Documents Approved', value: '89 / 131', sub: '68% complete' },
    { label: 'Pending Reviews', value: '23', sub: '5 overdue' },
  ];

  return (
    <div className="p-6">
      <h2 className="text-2xl font-bold text-white">Compliance Tracking</h2>
      <p className="text-sm text-usa-silver mt-1 mb-6">Monitor document approvals and regulatory status</p>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
        {scores.map((s, i) => (
          <motion.div
            key={s.label}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.05, ease }}
            className="bg-usa-elevated border border-usa-border rounded-xl p-5"
          >
            <p className="text-xs text-usa-silver uppercase tracking-wider">{s.label}</p>
            <p className="text-2xl font-bold text-white mt-2">{s.value}</p>
            <p className="text-xs text-usa-muted mt-1">{s.sub}</p>
          </motion.div>
        ))}
      </div>

      <div className="bg-usa-elevated border border-usa-border rounded-xl p-8 text-center">
        <ShieldCheck size={48} className="text-usa-blue mx-auto mb-4" strokeWidth={1.5} />
        <h3 className="text-lg font-semibold text-white mb-2">Compliance Dashboard</h3>
        <p className="text-sm text-usa-silver mb-4">Full compliance tracking coming soon</p>
      </div>
    </div>
  );
}

/* ─── Phase Gates view ─── */
function PhaseGatesView() {
  return (
    <div className="p-6">
      <h2 className="text-2xl font-bold text-white">Phase Gate Monitor</h2>
      <p className="text-sm text-usa-silver mt-1 mb-6">Track progress across 8 deployment phases</p>

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        {phases.map((phase, i) => (
          <motion.div
            key={phase.name}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.05, ease }}
            className="bg-usa-elevated border border-usa-border rounded-xl p-5"
          >
            <div className="flex items-center justify-between mb-3">
              <span className="w-6 h-6 rounded-full bg-usa-blue flex items-center justify-center text-[11px] font-bold text-white">
                {i}
              </span>
              <span className="text-xs text-usa-silver">{phase.progress}%</span>
            </div>
            <p className="text-sm font-semibold text-white mb-2">{phase.name.split(': ')[1]}</p>
            <div className="h-1.5 bg-usa-border rounded-full overflow-hidden mb-3">
              <motion.div
                initial={{ width: 0 }}
                animate={{ width: `${phase.progress}%` }}
                transition={{ duration: 0.8, ease }}
                className="h-full rounded-full"
                style={{ backgroundColor: phase.color }}
              />
            </div>
            <span
              className="inline-block text-[10px] font-semibold px-2 py-0.5 rounded"
              style={{
                backgroundColor: phase.progress === 100 ? 'rgba(16,185,129,0.15)' : phase.progress > 0 ? 'rgba(0,53,148,0.15)' : 'rgba(30,58,95,0.3)',
                color: phase.progress === 100 ? '#FFFFFF' : phase.progress > 0 ? '#B0B7BC' : '#888888',
              }}
            >
              {phase.progress === 100 ? 'Complete' : phase.progress > 0 ? 'In Progress' : 'Not Started'}
            </span>
          </motion.div>
        ))}
      </div>
    </div>
  );
}

/* ─── Main Admin component ─── */
export default function Admin() {
  const [activeView, setActiveView] = useState<AdminView>('dashboard');
  const [sidebarOpen, setSidebarOpen] = useState(false);

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [activeView]);

  const renderView = () => {
    switch (activeView) {
      case 'dashboard':
        return <DashboardView />;
      case 'documents':
        return <DocumentsView />;
      case 'compliance':
        return <ComplianceView />;
      case 'phase-gates':
        return <PhaseGatesView />;
      case 'governance':
        return <PlaceholderView title="DAO Governance" subtitle="Manage proposals, votes, and governance records" icon={Users} />;
      case 'security':
        return <PlaceholderView title="Security Audit Logs" subtitle="Monitor security events and audit trails" icon={Lock} />;
      case 'finance':
        return <PlaceholderView title="Financial Overview" subtitle="USA Purse balances and transaction history" icon={DollarSign} />;
      case 'agreements':
        return <PlaceholderView title="Legal Agreements" subtitle="Track agreements, versions, and signatures" icon={FileSignature} />;
      case 'exhibits':
        return <PlaceholderView title="Exhibits & Attachments" subtitle="Browse exhibit files and linked documents" icon={BarChart3} />;
      case 'launch-gates':
        return <PlaceholderView title="Launch Gates" subtitle="Checklist tracking for launch readiness" icon={Rocket} />;
      case 'settings':
        return <PlaceholderView title="Admin Settings" subtitle="Configure platform preferences and notifications" icon={Settings} />;
      default:
        return <DashboardView />;
    }
  };

  return (
    <div className="min-h-[100dvh] bg-usa-black text-white font-inter">
      <Sidebar
        activeView={activeView}
        onViewChange={setActiveView}
        isOpen={sidebarOpen}
        onToggle={() => setSidebarOpen(!sidebarOpen)}
      />

      {/* Main content area */}
      <div className="lg:ml-[260px] min-h-[100dvh] flex flex-col">
        <TopBar onMenuToggle={() => setSidebarOpen(!sidebarOpen)} />
        <main className="flex-1 overflow-y-auto">
          <AnimatePresence mode="wait">
            <motion.div
              key={activeView}
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.2, ease }}
            >
              {renderView()}
            </motion.div>
          </AnimatePresence>
        </main>
      </div>
    </div>
  );
}
